version: '3'

services:
  web:
    image: nginx
    container_name: "${APP_SLUG}-web"
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - '8080:80'
    restart: always
    depends_on:
      - php
      - db

  php:
    build:
      context: ./.docker/
    container_name: "${APP_SLUG}-php"
    restart: always
    volumes:
      - .:/var/www/html

  db:
    image: postgres:13.1
    container_name: "${APP_SLUG}-db"
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ~/.docker/data/laravel-permit/db:/var/lib/postgresql/data

  redis:
    image: redis:6.0-alpine
    container_name: "${APP_SLUG}-redis"
    volumes:
      - ./.docker/redis/redis.conf:/etc/redis/redis.conf
      - ~/.docker/data/laravel-permit/redis:/var/lib/redis
    ports:
      - '6379:6379'

  composer:
    image: composer
    container_name: "${APP_SLUG}-composer"
    volumes:
      - .:/var/www/html
    command: install
    working_dir: /var/www/html
    depends_on:
      - php

  artisan:
    build:
      context: ./.docker/
    container_name: "${APP_SLUG}-artisan"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    working_dir: /var/www/html
    entrypoint: ['/var/www/html/artisan']
